console.log("arithmetic operator");
let a = 5;
let b = 3;
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a / b);
console.log(a % b);
console.log(a++);
console.log(a);
console.log(b);
console.log(--b);
console.log(b++);
console.log("*** comparison operator***");
console.log(a == b);